name:                backgammon
version:             0.1.0.0
github:              "githubuser/backgammon"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2019 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/backgammon#readme>

dependencies:
- base >= 4.7 && < 5
- servant-server
- aeson
- servant
- servant-client
- time
- base-compat
- mtl
- attoparsec
- bytestring
- string-conversions
- http-media
- wai
- warp
- directory
- text
- transformers
- utf8-string

library:
  source-dirs: src

executables:
  backgammon-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - backgammon
    - servant-server
    - aeson
    - servant
    - servant-client
    - servant-docs

tests:
  backgammon-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - backgammon
    - servant-server
    - aeson
